[Last Successful Call]
timestamp = 2020-03-27 18:52:22.039000+02:00
error_code = 0
error_message = None
elapsed = 13
credit_count = 1

[Last Failed Call]
timestamp = 2020-03-27 00:23:27.086733+02:00
error_code = 3
error_message = Internal error: Connection exception when conduction API call
elapsed = 0
credit_count = 0

[Current Session]
successful_calls = 0
failed_calls = 0
success_rate = 100.0

[All Time]
successful_calls = 374
failed_calls = 9
success_rate = 97.65

